-- Replace old templates with comprehensive template library
-- Each template has detailed section guidelines stored in structure JSONB

DELETE FROM public.prd_templates WHERE is_built_in = true;

INSERT INTO public.prd_templates (workspace_id, name, description, category, structure, use_count, is_built_in) VALUES

-- ══════════════════════════
-- PRODUCT (4)
-- ══════════════════════════
(NULL, 'Peter''s PRD', 'Concise PRD with evidence-driven problem statements, measurable goals, and phased launch planning.', 'product',
 '{"sections":[{"name":"Team","guidelines":"List people involved with roles (PM, Design, Engineering, Analytics, Marketing) in a table."},{"name":"Problem","guidelines":"Describe customer problem with concrete evidence. Include specific customer segment, what they struggle with, and data/research."},{"name":"Goals","guidelines":"Define one output goal with 2-3 input metrics. Specify metric name, target % change, and timeframe. Include non-goals."},{"name":"Requirements","guidelines":"Write user stories with P0 (must ship) and P1 (should ship) priorities. Include high-level solution and milestones."},{"name":"Launch Plan","guidelines":"Define experiment design with success criteria, phased rollout percentages, monitoring duration, and rollback criteria."}]}',
 0, true),

(NULL, 'Aakash''s PRD', 'Comprehensive 14-section PRD with impact sizing, key flows, and detailed launch planning for team alignment.', 'product',
 '{"sections":[{"name":"Problem","guidelines":"State problem as testable hypothesis in 1-2 sentences with customer pain and business opportunity."},{"name":"High Level Approach","guidelines":"Describe approach without over-constraining design. Few sentences max."},{"name":"Narrative","guidelines":"Include common use case, edge case, and before/after scenarios to create empathy."},{"name":"Goals","guidelines":"Include measurable goals with baseline/target metrics and immeasurable goals about experience."},{"name":"Metrics","guidelines":"Define north star metric, 2-3 secondary metrics, and guardrail metrics with thresholds."},{"name":"Impact Sizing Model","guidelines":"Show step-by-step calculations with assumptions and revenue impact estimate."},{"name":"Non-goals","guidelines":"Explicitly state what you are NOT doing and why to prevent scope creep."},{"name":"Solution Alignment","guidelines":"Define in/out scope and list open questions for design/engineering exploration."},{"name":"Key Features","guidelines":"List features in priority order with P0/P1/P2, size estimate (S/M/L), and description."},{"name":"Future Considerations","guidelines":"Features saved for later that inform current decisions."},{"name":"Key Flows","guidelines":"Walk through every click and state including empty, loading, and error states."},{"name":"Key Logic","guidelines":"State business rules clearly with conditions, concrete examples, and edge cases."},{"name":"Launch Plan","guidelines":"Define phases with entry/exit criteria, experiment design, and risks/dependencies."},{"name":"Key Milestones","guidelines":"Milestone table with dates, owners, status, and dependencies."}]}',
 0, true),

(NULL, 'Lenny''s 1-Pager', 'Concise 1-page template for products with testable hypotheses, evidence, and solution clarity.', 'product',
 '{"sections":[{"name":"Description","guidelines":"2-3 sentences max. A stranger should understand the product. No jargon."},{"name":"Problem","guidelines":"Single sentence testable hypothesis focused on specific problem. Solution-agnostic."},{"name":"Why","guidelines":"Back up hypothesis with 3-5 data points. Include devil''s advocate section questioning evidence."},{"name":"Success","guidelines":"Define specific, measurable success metric with % change target."},{"name":"Audience","guidelines":"Specify user segment, platform, geography, and size. Explain why focus here first."},{"name":"What","guidelines":"Describe what users experience, not internal architecture. Walk through core experience."},{"name":"How","guidelines":"Specify approach (Build/Experiment/Prototype). Include technical considerations and risks."},{"name":"When","guidelines":"Timeline with milestones and confidence level."}]}',
 0, true),

(NULL, 'Product Brief for AI', 'Structured brief optimized for AI coding tools with 12 sections for direct implementation.', 'product',
 '{"sections":[{"name":"tl;dr","guidelines":"2-3 sentence summary with problem, core benefits, key features, and target audience."},{"name":"Goals","guidelines":"3-5 business goals with metrics, 3-5 user goals, and 2-3 non-goals."},{"name":"User Stories","guidelines":"Personas with stories in format: As [USER], I want [ACTION], so that [BENEFIT]."},{"name":"Functional Requirements","guidelines":"Group features by area and priority (P0/P1/P2). Be specific about behavior."},{"name":"User Experience","guidelines":"Entry point, first-time experience, core experience with step-by-step UI flows."},{"name":"Narrative","guidelines":"200-300 word user-centric story showing challenge, product solution, and positive outcome."},{"name":"Success Metrics","guidelines":"User metrics (DAU, completion, NPS), business metrics (revenue, conversion), technical metrics."},{"name":"Technical Considerations","guidelines":"Constraints, performance requirements, integration needs, architecture decisions."},{"name":"UI Architecture","guidelines":"Framework, component library, styling, state management, animations, accessibility."},{"name":"API & Backend","guidelines":"Framework, database, ORM, authentication, hosting, main endpoints."},{"name":"Performance & Scalability","guidelines":"Performance targets, scalability approach, accessibility requirements (WCAG)."},{"name":"Integration Points","guidelines":"Third-party services with purpose, SDK/library, configuration needed."}]}',
 0, true),

-- ══════════════════════════
-- TECHNICAL (8)
-- ══════════════════════════
(NULL, 'Feature Implementation Spec', 'Single-feature spec with exact acceptance criteria, edge cases, files to touch, and test plans.', 'technical',
 '{"sections":[{"name":"Feature Summary","guidelines":"1-2 sentences: what, why, who. Define in/out scope, prerequisites, dependencies."},{"name":"Acceptance Criteria","guidelines":"Numbered list split into Must-Have (P0), Should-Have (P1), Nice-to-Have (P2)."},{"name":"User Flow","guidelines":"Step-by-step happy path with alternate paths and specific UI components."},{"name":"Edge Cases & Error States","guidelines":"Input validation, system errors, permissions, empty states, rate limiting."},{"name":"Technical Approach","guidelines":"Files to create/modify with paths. Data flow from UI to database and back."},{"name":"Dependencies & Risks","guidelines":"Upstream/downstream dependencies, performance/security risks, rollback strategy."},{"name":"Test Plan","guidelines":"Manual testing checklist, unit/integration/E2E tests, regression checks."}]}',
 0, true),

(NULL, 'Technical Design Document', 'Architecture, data model, APIs, testing, deployment, security, and performance for engineers.', 'technical',
 '{"sections":[{"name":"Product Overview","guidelines":"Problem solved, user scenarios, benefits, KPIs, short-term vs long-term impact."},{"name":"Architecture","guidelines":"How components connect: frontend, backend, database, external services. Communication protocols and patterns."},{"name":"Data Model","guidelines":"Core entities with fields and types. Relationships, storage technology, caching strategy."},{"name":"Testing Plan","guidelines":"Unit, integration, E2E, performance tests. CI integration and code coverage targets."},{"name":"Deployment Plan","guidelines":"Environment setup, CI/CD pipeline, preview deployments, rollback strategy."},{"name":"Security & Performance","guidelines":"Auth, input validation, secrets management. Performance targets, optimization, monitoring."}]}',
 0, true),

(NULL, 'App Architecture Plan', 'Plan your system architecture before you start building. Covers data model, API design, auth, integrations, and deployment — everything an AI coding agent needs to scaffold your app correctly from the start.', 'technical',
 '{"sections":[{"name":"System Overview","guidelines":"What app does, who it is for, architecture type (monolith/microservices/serverless)."},{"name":"Data Model","guidelines":"Every core entity with fields and types. Relationships, indexes, unique constraints."},{"name":"API Design","guidelines":"API routes grouped by resource with METHOD, auth, request body, response format."},{"name":"Auth & Permissions","guidelines":"Auth provider, methods, roles, enforcement strategy, multi-tenancy approach."},{"name":"Third-Party Services","guidelines":"Each service: name, purpose, SDK, config (env vars), failure handling."},{"name":"Frontend Architecture","guidelines":"Framework, component library, styling, state management, pages with paths."},{"name":"Infrastructure & Deployment","guidelines":"Hosting, CI/CD pipeline, environment configs, required environment variables."}]}',
 0, true),

(NULL, 'Database Schema Design', 'Database design with entities, relationships, indexes, access patterns, migrations, and security.', 'technical',
 '{"sections":[{"name":"Overview & Goals","guidelines":"Database technology, hosting, rationale. Design priorities: read/write heavy, normalization, scale."},{"name":"Core Entities","guidelines":"All tables with fields, types, constraints. Mark PK, FK, UQ, IDX, nullable."},{"name":"Relationships & Constraints","guidelines":"All relationships with FK behavior (CASCADE, SET NULL, RESTRICT). Business rules."},{"name":"Indexes & Performance","guidelines":"Required indexes with type and supported query. N+1 risks, pagination, caching."},{"name":"Access Patterns","guidelines":"Most common queries with SQL, frequency, indexes used."},{"name":"Migration Plan","guidelines":"Migration tool, workflow, seed data strategy, zero-downtime approach."},{"name":"Security & Privacy","guidelines":"Sensitive data, encryption, compliance (GDPR, CCPA), data retention policies."}]}',
 0, true),

(NULL, 'API Documentation', 'This template provides a comprehensive guide for documenting APIs, including purpose, functionalities, architecture, authentication, error handling, and endpoints.', 'technical',
 '{"sections":[{"name":"API Overview","guidelines":"What API does, style (REST/GraphQL), base URL, versioning, rate limiting, data format."},{"name":"Authentication","guidelines":"Setup steps, usage in requests, curl examples for each auth method."},{"name":"Endpoints","guidelines":"For each: METHOD /path, description, auth, parameters, request/response body, errors."},{"name":"Error Handling","guidelines":"Error response format, error code reference, retry strategy."},{"name":"Code Examples","guidelines":"Working examples in cURL, JavaScript/TypeScript, and Python."},{"name":"Webhooks & Events","guidelines":"Available events, payload format, signature verification, retry policy."},{"name":"SDKs, Rate Limits & Support","guidelines":"Official SDKs, rate limit tiers, status page, changelog URLs."}]}',
 0, true),

(NULL, 'AI Coding Rules & Standards', 'Define the conventions, patterns, and rules for AI coding assistants working on your codebase. Generates a comprehensive rules file (like CLAUDE.md or .cursorrules) that keeps AI output consistent with your project.', 'technical',
 '{"sections":[{"name":"Project Overview","guidelines":"Project description, maturity level, key technologies, repository structure."},{"name":"Tech Stack & Conventions","guidelines":"Every major technology with version and project-specific conventions."},{"name":"Code Style Rules","guidelines":"Naming conventions, import order, export preferences, TypeScript strictness, formatting."},{"name":"Component & Architecture Patterns","guidelines":"Component structure, data fetching, state management, API route patterns."},{"name":"Do''s and Don''ts","guidelines":"Explicit rules with concrete examples. Cover React, TypeScript, styling, architecture."},{"name":"Testing & Quality","guidelines":"Testing frameworks, test file naming, what to test, linting/formatting config."},{"name":"Common Pitfalls","guidelines":"Deprecated patterns, environment quirks, files needing extra care, known bugs."}]}',
 0, true),

(NULL, 'Refactoring Plan', 'Engineering plan for codebase refactoring with problem analysis, target state, and migration strategy.', 'technical',
 '{"sections":[{"name":"Current State","guidelines":"For each problem: module/file, what is wrong (specific), impact (build time, errors, confusion)."},{"name":"Target State","guidelines":"New patterns with before/after examples. Objectively verifiable completion criteria."},{"name":"Motivation & Urgency","guidelines":"Why now: blocked feature, scaling issue, recurring incidents. Cost of not refactoring."},{"name":"Scope & Boundaries","guidelines":"What IS and IS NOT being changed. Break into phases if independent."},{"name":"Migration Strategy","guidelines":"Approach: strangler fig, big bang, or incremental. How old/new coexist."},{"name":"Implementation Steps","guidelines":"Ordered steps, each leaving codebase deployable. Files changed, PR size."},{"name":"Risk Assessment & Rollback","guidelines":"For each risk: likelihood, impact, mitigation, rollback. Point of no return."}]}',
 0, true),

(NULL, 'Spec for AI Prototyping', 'Self-contained spec for AI prototyping tools (v0, Bolt, Lovable) with design, tech stack, and flows.', 'technical',
 '{"sections":[{"name":"Product Overview","guidelines":"Core concept, who it is for, primary user action. Scope for prototype vs later."},{"name":"Design & Visual Style","guidelines":"Component library, color scheme (hex codes), theme, typography, reference sites."},{"name":"Tech Stack","guidelines":"Framework, language, database, ORM, auth, hosting, key libraries."},{"name":"Pages & Navigation","guidelines":"Every page with URL path, purpose, navigation structure, auth requirements."},{"name":"Core User Flows","guidelines":"2-4 most important interactions step-by-step with first win moment."},{"name":"Data Model & Backend","guidelines":"Core entities with fields. API endpoints, data persistence, background jobs."},{"name":"Key Components","guidelines":"UI components needing special attention with behavior and library preferences."},{"name":"AI Generation Notes","guidelines":"Features to skip/stub, performance considerations, patterns to follow/avoid."}]}',
 0, true),

-- ══════════════════════════
-- MARKETING (5)
-- ══════════════════════════
(NULL, 'Go-to-Market Plan', 'Strategic plan for product launch with market analysis, positioning, pricing, and success metrics.', 'marketing',
 '{"sections":[{"name":"Executive Summary","guidelines":"One paragraph covering what, who, when, how, and 90-day goal."},{"name":"Market Analysis","guidelines":"TAM/SAM/SOM with sources. Target segments, competitive landscape, differentiation."},{"name":"Product Positioning","guidelines":"Positioning statement: For [customer] who [need], [product] is [category] that [benefit]."},{"name":"Pricing Strategy","guidelines":"Model type, tiers with inclusions, price points with justification, competitive context."},{"name":"Promotional Plan","guidelines":"For each channel: tactic, timeline, owner, budget. Content plan and PR opportunities."},{"name":"Sales Strategy","guidelines":"Sales motion (self-serve, sales-assisted, outbound). Sales enablement materials."},{"name":"Success Metrics","guidelines":"30-day targets (awareness, activation) and 90-day targets (retention, growth)."}]}',
 0, true),

(NULL, 'Landing Page Brief', 'Creative brief for landing page with hero, value props, social proof, features, CTAs, and design.', 'marketing',
 '{"sections":[{"name":"Page Goal & Audience","guidelines":"Single primary conversion action. Traffic source, awareness level, key objection."},{"name":"Hero Section","guidelines":"Headline (8 words), subheadline (1-2 sentences), CTA button text, hero visual."},{"name":"Value Propositions","guidelines":"3-4 key benefits with headline, description, and visual suggestion."},{"name":"Social Proof","guidelines":"Testimonials, logo bar, usage stats, press mentions, case study snippet."},{"name":"Feature Showcase","guidelines":"3-5 features with benefit-oriented headline and 2-3 sentence description."},{"name":"CTA & Conversion","guidelines":"Primary CTA with button text, form fields, secondary CTA, trust builders."},{"name":"Design Direction","guidelines":"Color palette, typography, spacing, vibe, reference sites, mobile adaptations."}]}',
 0, true),

(NULL, 'PR FAQ', 'Amazon-style press release and FAQs announcing product launch from customer perspective.', 'marketing',
 '{"sections":[{"name":"Heading","guidelines":"Product name that target customer understands. One-sentence tagline."},{"name":"Subheading","guidelines":"Format: [Product] helps [customer] [achieve benefit]. Benefit-focused."},{"name":"Summary Paragraph","guidelines":"Press release lead with city, date, company, product, key benefit. 3-4 sentences."},{"name":"Problem Paragraph","guidelines":"Entirely from customer perspective. Quantify problem. DO NOT mention product."},{"name":"Solution Paragraph(s)","guidelines":"Lead with outcome. Explain in plain language. Highlight 2-3 key capabilities."},{"name":"Quotes & Getting Started","guidelines":"Company spokesperson quote, customer quote with real use case, how to start."},{"name":"External FAQs","guidelines":"Q&A for customers/journalists: pricing, differentiation, availability, security."},{"name":"Internal FAQs","guidelines":"Q&A for leadership: why now, revenue impact, build cost, risks, strategy fit."}]}',
 0, true),

(NULL, 'Release Notes', 'Template for documenting software release updates with features, improvements, and bug fixes.', 'marketing',
 '{"sections":[{"name":"Release Information","guidelines":"Product name, version (X.Y.Z), release date, release type, one-paragraph summary."},{"name":"New Features","guidelines":"For each: name, 1-2 sentence description, screenshot/GIF if visual. Note if beta."},{"name":"Improvements","guidelines":"Format: [Area]: [What improved and why it matters]. Specific numbers."},{"name":"Bug Fixes","guidelines":"Format: Fixed issue where [action] would [broken behavior]. Group by area."},{"name":"Known Issues","guidelines":"Issue description, impact, workaround, status (Investigating/In progress/Planned)."},{"name":"Breaking Changes & Migration","guidelines":"What changed, before/after behavior, action required, deadline."}]}',
 0, true),

(NULL, 'Product Launch Checklist', 'Comprehensive launch checklist organized chronologically from T-4 weeks to post-launch.', 'marketing',
 '{"sections":[{"name":"Pre-Launch (T-4 weeks)","guidelines":"Product readiness, content/marketing prep, internal readiness tasks."},{"name":"Pre-Launch (T-1 week)","guidelines":"Technical, marketing, and team final preparations. Staging, monitoring, feature flags."},{"name":"Launch Day","guidelines":"Morning (deploy, verify), midday (social, monitor), end of day (review, fix critical)."},{"name":"Post-Launch (Week 1)","guidelines":"Monitor metrics daily, track support, watch sentiment, respond to feedback, retrospective."},{"name":"Post-Launch (Month 1)","guidelines":"Review actual vs targets. Analyze funnel. Assess retention. Plan next release."},{"name":"Launch Roles & Contacts","guidelines":"RACI matrix with Launch Lead, Engineering, Marketing, Support, Design. Escalation path."}]}',
 0, true),

-- ══════════════════════════
-- RESEARCH (4)
-- ══════════════════════════
(NULL, 'User Personas', 'Research-grounded persona profiles with demographics, goals, pain points, and product implications.', 'research',
 '{"sections":[{"name":"Persona Name","guidelines":"Memorable descriptive name (e.g., Startup Sarah). Photo suggestion."},{"name":"Demographics","guidelines":"Only demographics influencing product: age, job title, company size, technical skill."},{"name":"Goals","guidelines":"Product goals, career goals, and Jobs-To-Be-Done format."},{"name":"Pain Points","guidelines":"What frustrates, frequency, severity (Annoying/Painful/Blocking), current workaround."},{"name":"User Journey","guidelines":"How persona discovers, evaluates, adopts, and uses products. Decision factors."},{"name":"Behavioral Traits","guidelines":"Technology behavior, work style, personality. Early adopter vs pragmatist."},{"name":"Quotes from Research","guidelines":"3-5 real quotes from interviews/surveys revealing key insights."},{"name":"Product Implications","guidelines":"Design implications, feature priority, messaging that resonates."}]}',
 0, true),

(NULL, 'Customer Journey Map', 'Map customer experience across journey stages with pain points, moments of truth, and action plan.', 'research',
 '{"sections":[{"name":"Customer Persona","guidelines":"Demographics, behavior, needs/goals, challenges, preferred channels."},{"name":"Journey Stages","guidelines":"Map six stages: Awareness, Consideration, Decision, Onboarding, Retention, Advocacy."},{"name":"Pain Points & Moments of Truth","guidelines":"For each: stage, what goes wrong, severity, frequency, evidence."},{"name":"Opportunities for Improvement","guidelines":"Unmet needs, experience gaps, innovation areas, quick wins."},{"name":"Action Plan","guidelines":"Initiatives by urgency: Immediate, Near-term, Long-term with owner and effort."}]}',
 0, true),

(NULL, 'User Testing Plan', 'Usability testing plan with objectives, participants, scenarios, metrics, and decision framework.', 'research',
 '{"sections":[{"name":"Test Objectives","guidelines":"Primary questions to learn. Success criteria: completion rate, time, error rate, satisfaction."},{"name":"Participant Criteria","guidelines":"5-8 participants per segment. Target profile, exclusions, screening questions, incentive."},{"name":"Test Scenarios","guidelines":"Realistic scenarios without UI hints. One easy and one challenging scenario."},{"name":"Tasks","guidelines":"For each: what to accomplish, starting point, success criteria, time limit."},{"name":"Metrics for Success","guidelines":"Quantitative: completion %, time, errors, SUS. Qualitative: observations, mental model."},{"name":"Feedback Collection","guidelines":"During: think-aloud, recording, notes. Post: questionnaire, debrief interview."},{"name":"Analysis & Recommendations","guidelines":"Rate findings by severity/frequency. Prioritized recommendations with decision framework."}]}',
 0, true),

(NULL, 'Competitive Analysis Report', 'Competitor analysis with company profiles, feature comparison, SWOT, positioning, and insights.', 'research',
 '{"sections":[{"name":"Company Profiles","guidelines":"For each: overview, founded, revenue/funding, key products, leadership, recent moves."},{"name":"Product Comparison","guidelines":"Feature matrix. Deep dive on 3-5 most important features: your approach vs theirs."},{"name":"SWOT Analysis","guidelines":"For each competitor and yourself: Strengths, Weaknesses, Opportunities, Threats."},{"name":"Market Positioning & Pricing","guidelines":"Positioning map, brand perception, pricing comparison, acquisition channels."},{"name":"Strategic Insights","guidelines":"3-5 key takeaways. Advantages to protect, vulnerabilities to address, market gaps."}]}',
 0, true),

-- ══════════════════════════
-- PLANNING (4)
-- ══════════════════════════
(NULL, 'OKRs', 'Structured OKR template with objectives, key results, initiatives, alignment, and scoring.', 'planning',
 '{"sections":[{"name":"Objective","guidelines":"Qualitative, ambitious but achievable, time-bound, aligned to company strategy."},{"name":"Key Results","guidelines":"Format: [Verb] [metric] from [baseline] to [target] by [date]. Mix leading and lagging."},{"name":"Initiatives","guidelines":"1-3 projects per KR with name, owner, and effort estimate (S/M/L/XL)."},{"name":"Alignment","guidelines":"Company objectives supported, cross-team dependencies, strategic context."},{"name":"Key Stakeholders","guidelines":"Table: Role, Person, Responsibility. Escalation path for trade-offs."},{"name":"Timeline & Checkpoints","guidelines":"Week 2, Month 1, Mid-quarter, End of quarter milestones and review cadence."},{"name":"Risks and Mitigations","guidelines":"For each: what could go wrong, likelihood, which KRs affected, mitigation."},{"name":"Review & Scoring","guidelines":"Scoring 0.0-1.0 scale. Review process and retrospective questions."}]}',
 0, true),

(NULL, 'Founding Hypothesis', 'Jake Knapp framework: customer, problem, approach, competitors, and differentiation.', 'planning',
 '{"sections":[{"name":"Customer Identification","guidelines":"Be specific: not ''businesses'' but ''B2B SaaS companies with 10-50 employees''. Validate with research."},{"name":"Problem Definition","guidelines":"From customer perspective. Quantify pain. Distinguish root problem from symptoms."},{"name":"Solution Approach","guidelines":"Describe approach, not every feature. Why THIS approach vs alternatives considered."},{"name":"Competitive Analysis","guidelines":"For each competitor: name, strengths, weaknesses, why customers switch."},{"name":"Differentiation Strategy","guidelines":"Type: Experience/Speed/Price/Integration/Technology. Complete hypothesis statement."}]}',
 0, true),

(NULL, 'Product Strategy Document', 'Strategy covering vision, market analysis, OKRs, product strategies, roadmap, and risks.', 'planning',
 '{"sections":[{"name":"Product Vision & Mission","guidelines":"Vision: ambitious, stable over years. Mission: who you serve, value delivered, unique positioning."},{"name":"Market Analysis","guidelines":"3-5 industry trends. Competitor analysis. Target segments. TAM/SAM/SOM with sources."},{"name":"Objectives & Key Results","guidelines":"Ambitious time-bound objectives with 2-4 measurable KRs each. Company alignment."},{"name":"Product Strategies","guidelines":"Product development, marketing/sales, customer success strategies."},{"name":"Product Roadmap","guidelines":"Near-term, medium-term, long-term initiatives with goals and sequencing rationale."},{"name":"Risks & Success Criteria","guidelines":"Risks with likelihood/impact/mitigation. Success criteria at 3/6/12 months."}]}',
 0, true),

(NULL, 'Release Plan', 'Guide for planning product release with objectives, scope, stakeholders, timeline, and risks.', 'planning',
 '{"sections":[{"name":"Product Overview","guidelines":"Product/feature name, target audience, value proposition, release type."},{"name":"Release Objectives","guidelines":"Specific measurable outcomes with metric and target. Relevance to KPIs."},{"name":"Release Scope","guidelines":"Included features with priority, bug fixes, deferred items. Non-functional requirements."},{"name":"Stakeholders & RACI","guidelines":"RACI matrix mapping activities to Responsible/Accountable/Consulted/Informed."},{"name":"Release Timeline & Milestones","guidelines":"Milestone table with dates, owners, status. Deploy strategy and rollback."},{"name":"Risk Assessment","guidelines":"Risk matrix with likelihood, impact, mitigation, owner. Go/no-go criteria."},{"name":"Measurement & Success Criteria","guidelines":"Day-1, Week-1, Month-1 metrics. Post-release review format."}]}',
 0, true),

-- ══════════════════════════
-- QUALITY (3)
-- ══════════════════════════
(NULL, 'Bug Investigation & Fix Plan', 'Structured document for investigating, diagnosing, and fixing a bug. Covers symptoms, reproduction, root cause analysis, proposed fix, and verification — useful for complex bugs that need clear documentation.', 'quality',
 '{"sections":[{"name":"Bug Summary","guidelines":"Broken behavior in 1-2 sentences. Severity, affected users, first observed, business impact."},{"name":"Reproduction Steps","guidelines":"Exact numbered steps from clean state. Environment details, frequency, time-dependent factors."},{"name":"Expected vs. Actual Behavior","guidelines":"What SHOULD happen vs what ACTUALLY happens. Console errors, network issues."},{"name":"Root Cause Analysis","guidelines":"Investigation trail. Exact file path and function. Code path from user action to failure."},{"name":"Proposed Fix","guidelines":"Files to modify, changes needed. Why this addresses root cause. Alternative approaches."},{"name":"Test Plan","guidelines":"Manual verification, edge case checks, unit/integration/E2E tests to write."},{"name":"Prevention","guidelines":"Immediate actions: test coverage, validation. Systemic: type safety, architecture."}]}',
 0, true),

(NULL, 'Accessibility Compliance Checklist', 'A comprehensive checklist to ensure accessibility compliance in design, content readability, and navigation for all users, including those with disabilities.', 'quality',
 '{"sections":[{"name":"Accessibility Overview","guidelines":"Target standard, legal requirements, scope, tools (axe, Lighthouse, screen readers)."},{"name":"Perceivable","guidelines":"Alt text, captions, color contrast (4.5:1), responsive at 200% zoom."},{"name":"Operable","guidelines":"Keyboard navigation, logical tab order, skip-to-content, 44x44px touch targets."},{"name":"Understandable","guidelines":"Lang attribute, visible labels, specific error messages, confirmation for destructive actions."},{"name":"Robust","guidelines":"Semantic HTML, proper ARIA, screen reader testing (VoiceOver, NVDA, TalkBack)."},{"name":"Findings & Remediation Plan","guidelines":"Issues by severity with fix-by dates. Process improvements for ongoing compliance."}]}',
 0, true),

(NULL, 'Product Security Assessment', 'Security evaluation covering architecture, data security, auth, threats, and incident response.', 'quality',
 '{"sections":[{"name":"Product Overview","guidelines":"Functionality, target users, attack vectors. Tech stack, infrastructure, dependencies."},{"name":"Data Security","guidelines":"Data classification (Critical/Sensitive/Internal/Public). Encryption, hashing, compliance."},{"name":"Authentication & Authorization","guidelines":"Auth methods, session management, password policy, RBAC/ABAC, API security."},{"name":"Threat Analysis & Risk Assessment","guidelines":"For each threat: description, vector, likelihood, impact, current controls."},{"name":"Security Controls & Monitoring","guidelines":"Preventive: validation, CSP, CORS. Detective: logging, alerting, vulnerability scanning."},{"name":"Incident Response & Business Continuity","guidelines":"Detection, triage, containment, communication, recovery, post-mortem. Backup strategy."}]}',
 0, true),

-- ══════════════════════════
-- USABILITY (1)
-- ══════════════════════════
(NULL, 'Usability Test Plan', 'Practical usability testing with methodology, participants, scenarios, metrics, and session guide.', 'research',
 '{"sections":[{"name":"Test Overview","guidelines":"What usability questions to answer. Scope, what is NOT tested. Stakeholder RACI."},{"name":"Test Design","guidelines":"Methodology (Moderated/Unmoderated, Remote/In-person), session duration, participant count."},{"name":"Tasks & Scenarios","guidelines":"Realistic scenarios without UI hints. Tasks with success criteria and time limits."},{"name":"Metrics & Success Criteria","guidelines":"Completion %, time, errors, satisfaction. Pass/fail/conditional thresholds."},{"name":"Session Guide","guidelines":"Script: Intro (5min), Warm-up (5min), Tasks (30-40min), Debrief (10min)."},{"name":"Analysis & Recommendations","guidelines":"Findings by severity/frequency. Summary, highlight reel, recommendation deck."}]}',
 0, true);
